### ISSUE TITLE
Thêm 1 trường trong thông tin sản phẩm

### ISSUE THREAD

**Issue by PhongTranE** [tqt97/QuanLyKho#11]
Thêm trường thời gian sử dụng, để string và không bắt buộc.
1 lọ 180 viên -> liều dùng ngày 2 viên => dùng được 90 ngày (3 tháng)

**Comment by tqt97** [comment]
> Thêm trường thời gian sử dụng, để string và không bắt buộc. 1 lọ 180 viên -> liều dùng ngày 2 viên => dùng được 90 ngày (3 tháng)

đã có cột liều dùng,số lượng. giờ thêm 1 cột là thời gian sử dụng, tách riêng ra vậy đúng không a

**Comment by PhongTranE** [comment]
đúng rồi, để kiểu tư vấn khách có hỏi dùng được trong bao lâu thì mình khỏi tính toán

**Comment by tqt97** [comment]
> đúng rồi, để kiểu tư vấn khách có hỏi dùng được trong bao lâu thì mình khỏi tính toán
oki a.

**Comment by tqt97** [comment]
Đã thêm [link](https://github.com/tqt97/QuanLyKho/commit/569bcf926d385200f71182bb33650a533700e520)
